version: '3.9'

services:
  postgres:
    image: postgres:14.3-alpine3.15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app
    ports:
      - "5431:5432"
